#pragma once

#include <Arduino.h>

// --- Pre-computed Trajectory Lookup Table ---
// Generated by generate_lut.py
// THIS IS A SAMPLE - YOU MUST RUN THE PYTHON SCRIPT TO GENERATE THE FULL FILE.

#define LUT_X_POINTS 8
#define LUT_Y_POINTS 5
#define LUT_Z_POINTS 5

const float LUT_X_MIN = 5.0000f;
const float LUT_X_MAX = 40.0000f;
const float LUT_Y_MIN = -2.0000f;
const float LUT_Y_MAX = 2.0000f;
const float LUT_Z_MIN = -2.0000f;
const float LUT_Z_MAX = 2.0000f;

struct Solution { float phi; float theta; };

// PROGMEM stores this large table in flash memory instead of RAM
const Solution lut[LUT_X_POINTS][LUT_Y_POINTS][LUT_Z_POINTS] PROGMEM = {
    { // X Index 0
        { // Y Index 0
            {{ 0.0f, 0.0f }, { 0.0f, 0.0f }, { 0.0f, 0.0f }, { 0.0f, 0.0f }, { 0.0f, 0.0f }}
        },
        // ... more data ...
    }
    // ... more data ...
};
